# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20180215_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(max_length=200),
        ),
    ]
