# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20180215_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hireDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
