# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_auto_20180216_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
    ]
